FROM python:3.11-slim

WORKDIR /app

# Install evidently
RUN pip install --no-cache-dir evidently>=0.4.0 sniffio


# Expose port
EXPOSE 8000

# Run evidently ui
CMD ["evidently", "ui", "--port", "8000", "--host", "0.0.0.0", "--workspace", "/app/workspace"]
